import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { Type } from 'class-transformer';
import {
  ArrayMaxSize,
  ArrayMinSize,
  IsArray,
  IsBoolean,
  IsIn,
  IsInt,
  IsISO8601,
  IsLatitude,
  IsLongitude,
  IsNumber,
  IsOptional,
  IsString,
  Max,
  MaxLength,
  Min,
  ValidateNested,
} from 'class-validator';
import { INCIDENT_TYPES, TELEMETRY_MAX_BATCH_SIZE } from '@rivo/config';

export class CreateIncidentDto {
  @ApiProperty({ enum: INCIDENT_TYPES })
  @IsIn(INCIDENT_TYPES as unknown as string[])
  type!: string;

  @ApiProperty()
  @Type(() => Number)
  @IsLatitude()
  lat!: number;

  @ApiProperty()
  @Type(() => Number)
  @IsLongitude()
  lng!: number;

  @ApiPropertyOptional({ description: 'Direction of travel the report applies to, in degrees from north.' })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  @Max(359)
  headingDeg?: number;

  @ApiPropertyOptional({ maxLength: 280 })
  @IsOptional()
  @IsString()
  @MaxLength(280)
  note?: string;
}

export class ConfirmIncidentDto {
  @ApiProperty({ description: 'true = still there, false = not there.' })
  @IsBoolean()
  confirmed!: boolean;

  @ApiPropertyOptional({ description: 'Reporter’s current position, used to weight the vote.' })
  @IsOptional()
  @Type(() => Number)
  @IsLatitude()
  lat?: number;

  @ApiPropertyOptional()
  @IsOptional()
  @Type(() => Number)
  @IsLongitude()
  lng?: number;
}

export class ListIncidentsDto {
  @ApiPropertyOptional({ description: 'Viewport as "minLng,minLat,maxLng,maxLat".' })
  @IsOptional()
  @IsString()
  @MaxLength(80)
  bbox?: string;

  @ApiPropertyOptional()
  @IsOptional()
  @Type(() => Number)
  @IsLatitude()
  lat?: number;

  @ApiPropertyOptional()
  @IsOptional()
  @Type(() => Number)
  @IsLongitude()
  lng?: number;

  @ApiPropertyOptional({ default: 5000, maximum: 50000 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(100)
  @Max(50000)
  radiusM?: number;

  @ApiPropertyOptional({ enum: INCIDENT_TYPES, isArray: true })
  @IsOptional()
  @IsArray()
  @IsIn(INCIDENT_TYPES as unknown as string[], { each: true })
  type?: string[];
}

export class TelemetrySampleDto {
  @ApiProperty()
  @Type(() => Number)
  @IsLatitude()
  lat!: number;

  @ApiProperty()
  @Type(() => Number)
  @IsLongitude()
  lng!: number;

  @ApiProperty({ description: 'Speed in km/h.', minimum: 0, maximum: 300 })
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  @Max(300)
  speedKph!: number;

  @ApiPropertyOptional({ minimum: 0, maximum: 359 })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(0)
  @Max(359)
  headingDeg?: number;

  @ApiPropertyOptional({ description: 'GPS accuracy in metres. Samples worse than 50 m are discarded.' })
  @IsOptional()
  @Type(() => Number)
  @IsNumber()
  @Min(0)
  accuracyM?: number;

  @ApiProperty({ description: 'ISO 8601 timestamp of the fix.' })
  @IsISO8601()
  recordedAt!: string;
}

export class TelemetryBatchDto {
  @ApiProperty({
    description:
      'Rotating pseudonymous session id generated by the client. Must NOT be a device id, advertising id or account id, and must be regenerated at least daily.',
    maxLength: 64,
  })
  @IsString()
  @MaxLength(64)
  sessionKey!: string;

  @ApiProperty({
    description: 'Explicit confirmation the user consented. A batch with consent=false is discarded.',
  })
  @IsBoolean()
  consent!: boolean;

  @ApiProperty({ type: [TelemetrySampleDto], maxItems: TELEMETRY_MAX_BATCH_SIZE })
  @IsArray()
  @ArrayMinSize(1)
  @ArrayMaxSize(TELEMETRY_MAX_BATCH_SIZE)
  @ValidateNested({ each: true })
  @Type(() => TelemetrySampleDto)
  samples!: TelemetrySampleDto[];
}
