/**
 * Writes docs/api/openapi.json and docs/api/ENDPOINTS.md from the live route
 * table, so the published API reference is generated from the code rather than
 * maintained by hand.
 *
 * Run: npm run openapi:generate -w @rivo/api
 */
import 'reflect-metadata';
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { VersioningType } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { SwaggerModule } from '@nestjs/swagger';

import { AppModule } from '../src/app.module';
import { buildOpenApiConfig } from '../src/openapi.config';

const OUT_DIR = resolve(__dirname, '../../../docs/api');

interface Operation {
  summary?: string;
  description?: string;
  tags?: string[];
  security?: Array<Record<string, unknown>>;
}

const METHODS = ['get', 'post', 'patch', 'put', 'delete'] as const;

function endpointsMarkdown(paths: Record<string, Record<string, Operation>>): string {
  const byTag = new Map<string, string[]>();

  for (const [path, operations] of Object.entries(paths)) {
    for (const method of METHODS) {
      const op = operations[method];
      if (!op) continue;

      const tag = op.tags?.[0] ?? 'other';
      const auth = op.security?.length
        ? Object.keys(op.security[0]).includes('admin')
          ? 'admin'
          : 'user'
        : 'public';
      const summary = (op.summary ?? '').replace(/\|/g, '\\|');

      const rows = byTag.get(tag) ?? [];
      rows.push(`| \`${method.toUpperCase()}\` | \`${path}\` | ${auth} | ${summary} |`);
      byTag.set(tag, rows);
    }
  }

  const total = [...byTag.values()].reduce((sum, rows) => sum + rows.length, 0);

  const sections = [...byTag.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([tag, rows]) => `## ${tag}\n\n| Method | Path | Auth | Summary |\n| --- | --- | --- | --- |\n${rows.sort().join('\n')}`);

  return [
    '# RIVO API — endpoint reference',
    '',
    '<!-- Generated by apps/api/scripts/generate-openapi.ts. Do not edit by hand. -->',
    '',
    `${total} operations. The machine-readable contract is [openapi.json](./openapi.json);`,
    'the running API also serves Swagger UI at `/api/docs` outside production.',
    '',
    '**Auth column** — `public`: no token; `user`: phone-OTP access token;',
    '`admin`: admin session token, further restricted by role (see `@RequireRoles`).',
    '',
    ...sections,
    '',
  ].join('\n');
}

async function main(): Promise<void> {
  const app = await NestFactory.create(AppModule, { logger: ['error'] });
  app.setGlobalPrefix('api');
  app.enableVersioning({ type: VersioningType.URI, defaultVersion: '1' });
  await app.init();

  try {
    const serverUrl = process.env.API_BASE_URL ?? 'http://localhost:3000';
    const document = SwaggerModule.createDocument(app, buildOpenApiConfig(serverUrl));

    mkdirSync(OUT_DIR, { recursive: true });
    writeFileSync(resolve(OUT_DIR, 'openapi.json'), `${JSON.stringify(document, null, 2)}\n`);
    writeFileSync(
      resolve(OUT_DIR, 'ENDPOINTS.md'),
      endpointsMarkdown(document.paths as Record<string, Record<string, Operation>>),
    );

    const count = Object.values(document.paths).reduce(
      (sum, ops) => sum + METHODS.filter((m) => (ops as Record<string, unknown>)[m]).length,
      0,
    );
    console.log(`wrote docs/api/openapi.json and docs/api/ENDPOINTS.md (${count} operations)`);
  } finally {
    await app.close();
  }
}

void main().then(
  () => process.exit(0),
  (err) => {
    console.error(err);
    process.exit(1);
  },
);
